// Stable artifact identities for F4, and the retry rules that go with them.
//
// The bug this exists to prevent: artifact names keyed on github.run_attempt. A rerun of a failed
// job bumps run_attempt, so the retried cell uploads under a NEW name, the closeout then sees the
// stale attempt-1 copy AND the fresh attempt-2 copy for what it believes is one cell, and the
// verdict silently depends on which one a glob happened to return first. Worse, the prepared
// artifact is not regenerated by a partial rerun, so attempt-2 samples can end up paired with
// attempt-1 evidence.
//
// So: every artifact name is keyed on run_id alone, a cell's artifact is overwritten in place on
// retry, and the run identity itself (run_id, attempt, sha) travels INSIDE the payload where a
// duplicate can be detected rather than hidden in a filename.

export const STAGES = { CHROMIUM: 'chromium', ENGINES: 'engines', CLOSEOUT: 'closeout' }

export function preparedArtifact(runId) {
  return 'r10-f4-prepared-' + runId
}

export function cellArtifact({ engine, replicate, runId }) {
  return 'r10-f4-sample-' + engine + '-r' + replicate + '-' + runId
}

export function stageArtifact({ stage, runId }) {
  return 'r10-f4-stage-' + stage + '-' + runId
}

export function timingGateArtifact(runId) {
  return 'r10-f4-timing-gate-' + runId
}

/** Every artifact name a run produces, for the contract test to inspect for attempt leakage. */
export function allArtifactNames({ runId }) {
  return [preparedArtifact(runId), timingGateArtifact(runId)]
}

/** The identity a payload must carry. Attempt is recorded, never used in a name. */
export function runIdentity(env = process.env) {
  return {
    runId: env.GITHUB_RUN_ID || null,
    attempt: env.GITHUB_RUN_ATTEMPT || null,
    sha: env.GITHUB_SHA || null,
    ref: env.GITHUB_REF || null,
    job: env.GITHUB_JOB || null,
  }
}

/** A duplicate is two documents claiming the same (runId, cell). This is the check that catches a
 *  naming scheme that leaks attempt into the filename even when the aggregate would not notice. */
export function duplicateRunIds(docs) {
  const seen = new Set()
  const duplicates = []
  for (const doc of docs) {
    const key = doc.runId + '|' + doc.browser + ':' + doc.replicate
    if (seen.has(key)) duplicates.push(key)
    else seen.add(key)
  }
  return duplicates
}

/**
 * Merge documents harvested from several download attempts into one document per cell. This is the
 * retry semantics in one place: a rerun re-executes failed cells and re-uploads under the SAME
 * run_id-keyed name, cells that already succeeded are not re-executed and keep the artifact from
 * the earlier attempt, and the closeout therefore sees prior-good and retried cells side by side.
 *
 * Two copies of the same cell at the SAME attempt index are a real conflict rather than a retry,
 * and are reported instead of silently resolved: that can only happen if something outside this
 * lane wrote a second document under a stable name.
 * @param {string[]} expected exact cells
 * @param {object[]} docs every document found, in harvest order
 * @param {string} runId the run whose cells are wanted
 */
export function mergeCells(expected, docs, runId) {
  const out = new Map()
  const rejected = []
  const duplicated = []
  // attemptIndex is the numeric field validate.mjs writes; attempt is the raw Actions string. Read
  // both so a payload carrying only one of them still orders correctly.
  const attemptOf = (d) => Number(d.attemptIndex ?? d.attempt ?? 0)
  for (const doc of docs) {
    if (!doc || doc.runId !== runId) {
      rejected.push((doc?.runId || 'unknown') + '|' + (doc?.browser || '?') + ':' + (doc?.replicate ?? '?'))
      continue
    }
    const key = doc.browser + ':' + doc.replicate
    const prior = out.get(key)
    // Highest attempt wins, so a retried cell supersedes the copy it replaced.
    if (!prior) {
      out.set(key, doc)
    } else if (attemptOf(doc) > attemptOf(prior)) {
      out.set(key, doc)
    } else if (attemptOf(doc) === attemptOf(prior)) {
      duplicated.push(key)
    }
  }
  return {
    cells: out,
    rejected,
    duplicated: [...new Set(duplicated)],
    missing: expected.filter((key) => !out.has(key)),
  }
}